### ISSUE TITLE
$variation_data doesn't contain field values

### ISSUE THREAD

**Issue by circularone** [isabelc/woocommerce-variation-description-radio-buttons#3]
The fields are saving fine and display on the front end but the values aren't able to display in the admin which means that unless you re enter all the descriptions the variations will be overwritten the next time you save a product.

public function variable_fields( $loop, $variation_data ) {

$variation_data in the above function doesn't actually contain the description field and as it also doesn't contain the variation ID I can't use it to get the description field value.

Can you help?

**Comment by isabelc** [comment]
Thanks for the report. I will look into this within the next 3 days.

**Comment by isabelc** [comment]
I just fixed this and made [a release](https://github.com/isabelc/woocommerce-variation-description-radio-buttons/releases/tag/0.9). Thanks again for the report.

**Comment by circularone** [comment]
Hi Isabel, thanks for fixing so quick. The fields save fine and the field looks much better in the admin now.

There's another problem now in that every product fails when adding to cart with the error "Sorry, this product cannot be purchased."

I'll have a look and see if I can spot what's up.

Cheers

**Comment by isabelc** [comment]
That will happen if the product is "Private".

**Comment by circularone** [comment]
The products aren't private. I ended up just adding a new description field myself and writing a new variable.php for the radio buttons and it's working fine. Thanks for the help!
